### ISSUE TITLE
Closure Compiler

### ISSUE THREAD

**Issue by buu700** [literalpie/Annotated-Angular-Roadmap#1]
Might be worth tracking the status of Angular (CLI) Closure Compiler support: https://github.com/angular/angular/issues/37234

**Comment by literalpie** [comment]
Hi, thanks for the suggestion. I hadn't seen that issue before. However, I'm trying to keep this focused on things that the Angular team is actively working on and all of the items in my list are from the official Angular roadmap, which doesn't mention anything about Closure. Do you have any resource that indicates they are committed to working in this in the next 3-6 months?

**Comment by buu700** [comment]
Ah okay, that makes sense. Based on that issue thread, it seems that they had to remove the existing Closure support because of a breaking change in TypeScript and haven't committed to bringing it back on a specific timeline.

(The CLI to my knowledge never took advantage of this capability, but it looks like the third-party package `angular-rollup` was able to extend it to do so.)
